//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitWrite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitWrite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Enter.
        /// </summary>
        public static string AcceptShortcutText {
            get {
                return ResourceManager.GetString("AcceptShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptText {
            get {
                return ResourceManager.GetString("AcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amending....
        /// </summary>
        public static string AmendingText {
            get {
                return ResourceManager.GetString("AmendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitWrite.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string CancelAcceleratorText {
            get {
                return ResourceManager.GetString("CancelAcceleratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit body (optional).
        /// </summary>
        public static string CommitBodyHint {
            get {
                return ResourceManager.GetString("CommitBodyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit title (required).
        /// </summary>
        public static string CommitSubjectHint {
            get {
                return ResourceManager.GetString("CommitSubjectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing.
        /// </summary>
        public static string CommittingHeaderText {
            get {
                return ResourceManager.GetString("CommittingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing....
        /// </summary>
        public static string CommittingText {
            get {
                return ResourceManager.GetString("CommittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing to {0} - {1}.
        /// </summary>
        public static string CommittingToBranchText {
            get {
                return ResourceManager.GetString("CommittingToBranchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string CopyShortcutText {
            get {
                return ResourceManager.GetString("CopyShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+X.
        /// </summary>
        public static string CutShortcutText {
            get {
                return ResourceManager.GetString("CutShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutText {
            get {
                return ResourceManager.GetString("CutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Discard.
        /// </summary>
        public static string DiscardAcceleratorText {
            get {
                return ResourceManager.GetString("DiscardAcceleratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarding....
        /// </summary>
        public static string DiscardingText {
            get {
                return ResourceManager.GetString("DiscardingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string DiscardShortcutText {
            get {
                return ResourceManager.GetString("DiscardShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string DiscardText {
            get {
                return ResourceManager.GetString("DiscardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes to this commit message. Do you want to save your changes?.
        /// </summary>
        public static string ExitConfirmationBodyText {
            get {
                return ResourceManager.GetString("ExitConfirmationBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit.
        /// </summary>
        public static string ExitConfirmationHeaderText {
            get {
                return ResourceManager.GetString("ExitConfirmationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file:.
        /// </summary>
        public static string FileLoadErrorMessage {
            get {
                return ResourceManager.GetString("FileLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File load error.
        /// </summary>
        public static string FileLoadErrorTitle {
            get {
                return ResourceManager.GetString("FileLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        public static string NoAcceleratorText {
            get {
                return ResourceManager.GetString("NoAcceleratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string OKAcceleratorText {
            get {
                return ResourceManager.GetString("OKAcceleratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        public static string PasteShortcutText {
            get {
                return ResourceManager.GetString("PasteShortcutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PasteText {
            get {
                return ResourceManager.GetString("PasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream PopSound {
            get {
                return ResourceManager.GetStream("PopSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebasing....
        /// </summary>
        public static string RebasingText {
            get {
                return ResourceManager.GetString("RebasingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveAcceleratorText {
            get {
                return ResourceManager.GetString("SaveAcceleratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        public static string YesAcceleratorText {
            get {
                return ResourceManager.GetString("YesAcceleratorText", resourceCulture);
            }
        }
    }
}
